drop table cert_ratings;

create table cert_ratings
(
	cr_id int not null generated by default as identity,
	rating varchar(20),
	_desc varchar(80),
	obsolete varchar(3)
) unique primary index (cr_id);